### ISSUE TITLE
I can't get it to post an image

### ISSUE THREAD

**Issue by fortepc** [valerio-vaccaro/node-red-contrib-mastodon#4]
I've got it working fine for text post by passing a json object

```json
{
    "text": "Hello World"
}
```

but when I try to pass an image to it, it does absolutely nothing. 

```json
{
    "text": "Hello World",
    "image": "http://pbs.twimg.com/media/FmiFHv4WIAEaKh8.jpg"
}
```

it doesn't even post `undefined` like it would if I just pump a default timestamp inject into it. It just stays at "Waiting" status.

**Comment by b-neufeld** [comment]
See this thread, it might help: https://discourse.nodered.org/t/node-red-contrib-mastodon/70103

What I'm wondering is if an image can be posted as either a binary buffer or by passing a URL? I can't seem to get an image posting with a URL.

**Comment by Guzbikes** [comment]
I am also trying to post an image to my self-hosted Mastodon instance. I can get it to post text. But when I pass it the file path for a local image file, I also get no response from the sendMessage node.

I have seen a couple different messages in the Node Red logs:

- "Unhandled rejection Error: read ECONNRESET
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)"

- "Unhandled rejection Error: Client network socket disconnected before secure TLS connection was established at connResetException (node:internal/errors:704:14) at TLSSocket.onConnectEnd (node:_tls_wrap:1588:19) at TLSSocket.emit (node:events:549:35) at endReadableNT (node:internal/streams/readable:1359:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"

Does anyone else have this working to post a local image from the machine Node Red is running on? I am able to display the same image using the same local file path using: https://flows.nodered.org/node/node-red-contrib-image-tools so I don't think it is a Node Red or file permissions problem.

Any ideas?

**Comment by b-neufeld** [comment]
> Any ideas?

Here's my working setup in case it helps. 

Basic flow: On a timer, grab an image from a URL, write it to Node-RED working directory, then create the Mastodon message (that feeds into the sendMessage node). I crossed out some Twitter stuff running in parallel:
![image](https://github.com/valerio-vaccaro/node-red-contrib-mastodon/assets/18536548/781581a4-30d6-40bf-9344-0b2e79563aff)

Write file node:
![image](https://github.com/valerio-vaccaro/node-red-contrib-mastodon/assets/18536548/c8e5e83f-af2c-4a5d-b3e2-673f105e6b37)

Setting payload.image and payload.text in a change node, which is passed to sendMessage:
![image](https://github.com/valerio-vaccaro/node-red-contrib-mastodon/assets/18536548/de19d6b8-090b-4f6d-81b2-e26c320d8240)

**Comment by Guzbikes** [comment]
I am still trying to get it to post an image. In my case the image is created and stored locally. I want it to post that image to my self-hosted Mastodon instance. The node works fine posting text, but when I add an image, I get nothing but the error messages: 

- "Unhandled rejection Error: read ECONNRESET
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)"

- "Unhandled rejection Error: Client network socket disconnected before secure TLS connection was established at connResetException (node:internal/errors:704:14) at TLSSocket.onConnectEnd (node:_tls_wrap:1588:19) at TLSSocket.emit (node:events:549:35) at endReadableNT (node:internal/streams/readable:1359:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"

**Comment by hardillb** [comment]
I've just opened a PR that will allow `msg.payload.image` to be a buffer so removing the need to save to a temp file.

Also adds Alt Text support with `msg.payload.description`
